### ISSUE TITLE
Main Product Page Breaks beacuse of  windows.okenWidgetApi.initWidget

### ISSUE THREAD

**Issue by hamza4600** [okendo/okendo-reactjs-example#5] opened 2023-05-09 09:20 UTC
The page is broken when we call the `windows.okenWidgetApi.initWidget` is main cause of breaking pages and this function is responsible for showing the reviews on the page from Okendo API

![Screenshot 2023-05-09 141905](https://user-images.githubusercontent.com/78164997/237052535-800be02e-967a-47b8-8ad7-a045b47c5d40.png)

I have done a fix by my self  it works fine for me

**Comment by hamza4600** [comment] 2023-05-09 09:22
@mattgarven  if you want to assign this task to I it will be great I a done a fix in live site for this 
👍 : @tomokendo  @Zwyx

**Comment by Zwyx** [comment] 2023-05-09 12:20
Hi @hamza4600, thanks for creating this issue. Feel free to create a PR or just tell us more about your fix, we'll investigate :+1:

**Comment by Zwyx** [comment] 2023-05-10 01:49
Hi @hamza4600, I can't reproduce the problem you're experiencing. Could you please tell us more about it and provide an example code/repo?

**Comment by hamza4600** [comment] 2023-05-10 11:22
@Zwyx I updated the Okendo code in the next js app which is an E-commerce store and Followed this Code implementation EVERYTHING WORKING FINE  and then I build the application the Product Pages were broken and the main Error coming in the console was the above Image then I made a change to the code that's  work fine 

I added a few checks 
In Next js I used it as a client component

**Comment by Zwyx** [comment] 2023-05-16 08:21
Fixed by https://github.com/okendo/okendo-reactjs-example/pull/7 and 
https://github.com/okendo/okendo-reactjs-example/pull/8.

Thanks Hamza!

**Closed as completed by Zwyx** 2023-05-16 08:21 UTC
